/**
 * Every file bootstrap-tools writes into bootstrap says so, and names
 * bootstrap-tools as the writer (owner, 2026-09-30, bean `xsqm`).
 *
 * The set is DERIVED from what is on disk, per kind, not listed file by file:
 * a new schema or a new diagram's picture is covered without an edit here,
 * and one that lacks the note fails.
 */
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { GENERATED_BY, TOOLS_REPOSITORY, generatedBanner, generatedScripts, wholeFileGenerated } from "./generated-by.ts";

const BOOTSTRAP = join(import.meta.dir, "..", "..", "bootstrap");
const inDir = (dir: string, ext: string) =>
  readdirSync(join(BOOTSTRAP, dir))
    .filter((f) => f.endsWith(ext))
    .map((f) => join(dir, f));

const GENERATED: Array<{ kind: string; files: string[] }> = [
  { kind: "published JSON Schemas", files: inDir("schemas", ".schema.json") },
  { kind: "the drawn schema page", files: ["schemas/README.md"] },
  { kind: "the vocabulary", files: ["ns.jsonld"] },
  { kind: "each Process's picture", files: inDir("processes", ".svg") },
];

describe("every generated file in bootstrap names bootstrap-tools as its writer", () => {
  for (const { kind, files } of GENERATED) {
    test(`${kind} (${files.length})`, () => {
      expect(files.length).toBeGreaterThan(0); // not vacuous
      const missing = files.filter((f) => !readFileSync(join(BOOTSTRAP, f), "utf-8").includes(GENERATED_BY));
      expect(missing).toEqual([]);
    });
  }

  test("the vocabulary also says it in RDF: prov:wasAttributedTo the tools repository", () => {
    const doc = JSON.parse(readFileSync(join(BOOTSTRAP, "ns.jsonld"), "utf-8")) as Record<string, unknown>;
    expect(doc["wasAttributedTo"]).toBe(TOOLS_REPOSITORY);
  });

  test("an AUTHORED file does not claim to be generated", () => {
    const authored = [...inDir("processes", ".bpmn"), "bootstrap.json"];
    const claiming = authored.filter((f) => readFileSync(join(BOOTSTRAP, f), "utf-8").includes(GENERATED_BY));
    expect(claiming).toEqual([]);
  });

  test("a PARTLY generated README claims only its marker regions, and every region says so at its top", () => {
    const text = readFileSync(join(BOOTSTRAP, "README.md"), "utf-8");
    const regions = [...text.matchAll(/<!-- ([\w:-]+):begin -->\n\n([\s\S]*?)<!-- \1:end -->/g)];
    expect(regions.length).toBeGreaterThan(0);
    for (const [, marker, body] of regions) expect(body!.startsWith("<!-- Generated by bootstrap-tools"), marker).toBe(true);
    const outside = text.replace(/<!-- ([\w:-]+):begin -->[\s\S]*?<!-- \1:end -->/g, "");
    expect(outside.includes(GENERATED_BY)).toBe(false);
    expect(wholeFileGenerated(text)).toBe(false);
  });

  test("every directory README opens with the notice, linking bootstrap-tools", () => {
    const dirs = readdirSync(BOOTSTRAP, { withFileTypes: true }).filter((d) => d.isDirectory() && !d.name.startsWith("."));
    const readmes = dirs.map((d) => join(d.name, "README.md")).filter((f) => { try { readFileSync(join(BOOTSTRAP, f)); return true; } catch { return false; } });
    expect(readmes.length).toBeGreaterThan(0);
    for (const f of readmes) {
      const text = readFileSync(join(BOOTSTRAP, f), "utf-8");
      const top = text.split("\n").slice(0, 3).join("\n");
      expect(top, f).toContain("This page was generated by [bootstrap-tools](" + TOOLS_REPOSITORY + ")");
      expect(wholeFileGenerated(text), f).toBe(true);
    }
  });
});

describe("the notice", () => {
  test("names the script, links it, and reads back", () => {
    const b = generatedBanner("scripts/x.ts", "the `a` entry (of b)", "change it", "section");
    expect(b).toContain(`[\`scripts/x.ts\`](${TOOLS_REPOSITORY}/blob/main/scripts/x.ts)`);
    expect(b).toContain("This section was generated by");
    expect(generatedScripts(b)).toEqual([{ script: "scripts/x.ts", from: "the `a` entry (of b)", instead: "change it" }]);
  });
});
