/**
 * The note every file bootstrap-tools writes into bootstrap carries: that it
 * is generated, by what, and what to change instead.
 *
 * @module bootstrap-tools/scripts/generated-by
 *
 * Owner, 2026-09-30 (bean `xsqm`): generated content needs "a header note that
 * content is autogenerated and (unique exception) reference the
 * bootstrap-tools as what generated". bootstrap otherwise names nothing
 * outside itself, and its tools repository is named only as the answer to
 * "what wrote this file?".
 *
 * Owner, 2026-10-01 (folio-assistant#1770), narrowing that exception: only a
 * README's visible notice may still carry the NAME (`generatedBanner`'s second
 * line). Every other generated note says "the bootstrap toolset" and gives the
 * repository as an ADDRESS, {@link TOOLS_REPOSITORY}, so it still answers
 * "what wrote this, and where do I change it?" without naming a layer above
 * bootstrap in its prose. One wording, here, so the check that every generated
 * file carries it (`generated-by.test.ts`) has one thing to look for.
 */

/** The repository that writes bootstrap's generated files. */
export const TOOLS_REPOSITORY = "https://github.com/litlfred/bootstrap-tools";

/** The phrase every note begins with — what the check looks for. */
export const GENERATED_BY = "Generated by the bootstrap toolset";

/** `Generated by the bootstrap toolset (<TOOLS_REPOSITORY>, <script>) from <from> — do not edit; <instead>.` */
export function generatedNote(script: string, from: string, instead: string): string {
  return `${GENERATED_BY} (${TOOLS_REPOSITORY}, ${script}) from ${from} — do not edit; ${instead}.`;
}

/** The visible notice's opening words, for a whole page or one region of a page. */
export type GeneratedUnit = "page" | "section";

/**
 * The notice a generated README carries at its TOP — or, for a README only
 * partly generated, at the top of each region a tool writes (owner,
 * 2026-10-01: *"README.mds and html need to have at top (this page was
 * autogenerated and link to bootstrap-tools)"*).
 *
 * Two lines, from one call so they cannot drift: an HTML comment carrying
 * {@link generatedNote} — what {@link GENERATED_BY} checks and what
 * {@link generatedScripts} reads back, invisible on a rendered page — and the
 * line a reader sees, linking bootstrap-tools and the script that wrote it.
 */
export function generatedBanner(script: string, from: string, instead: string, unit: GeneratedUnit = "page"): string {
  return [
    `<!-- ${generatedNote(script, from, instead)} -->`,
    `> *This ${unit} was generated by [bootstrap-tools](${TOOLS_REPOSITORY}) — [\`${script}\`](${TOOLS_REPOSITORY}/blob/main/${script}), from ${from}. Do not edit it here; ${instead}.*`,
  ].join("\n");
}

const NOTE = /Generated by the bootstrap toolset \(https:\/\/[^,\s]+, ([^)]+)\) from (.+?) — do not edit; (.+?)\.(?: -->|\s*$)/gm;

/** Every generated note in `text`, in order: which script, from what, and what to change instead. */
export function generatedScripts(text: string): { script: string; from: string; instead: string }[] {
  return [...text.matchAll(NOTE)].map((m) => ({ script: m[1]!, from: m[2]!, instead: m[3]! }));
}

/** `<!-- name:begin -->` … `<!-- name:end -->`, the regions a tool owns in a file somebody else may own. */
const REGION = /<!-- ([\w:-]+):begin -->[\s\S]*?<!-- \1:end -->/g;

/**
 * Whether a whole file is generated, rather than only some regions of it:
 * once every marker region is taken out, nothing is left — or what is left
 * itself carries a generated note, which is how a generator that owns
 * everything outside another's region marks its part (`schemas/README.md`).
 */
export function wholeFileGenerated(text: string): boolean {
  if (generatedScripts(text).length === 0) return false;
  const rest = text.replace(REGION, "").trim();
  return rest === "" || rest.includes(GENERATED_BY);
}
