#!/usr/bin/env bun
/**
 * Write — or with `--check`, verify — the generated sections of bootstrap's
 * `README.md`: `kg:processes`, `kg:files` and `kg:roles`.
 *
 * @module bootstrap-tools/scripts/readme-sections
 * @covers code
 *
 * The writers are in `readme-graph-sections.ts`; this is the command that runs
 * them where bootstrap-tools stands alone. Found missing by the standalone QA
 * of 2026-09-30: without it, bootstrap's README sections could only be
 * regenerated by a harness that hosts bootstrap, and nothing standalone would
 * notice them going stale.
 *
 * A section is written only between its own `<!-- <marker>:begin -->` and
 * `:end` markers, in the same form a hosting harness writes, so the two
 * cannot disagree: a blank line, the body, a blank line. A README without a
 * section's markers has not opted into it, and is left alone. A section that
 * says it could not determine its content (`skip`) leaves the region as it is.
 *
 * Usage: bun run bootstrap-tools/scripts/readme-sections.ts [--root ./bootstrap] [--check]
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { filesSection, processesSection, rolesSection, type GraphSection } from "./readme-graph-sections.ts";

export const SECTIONS: readonly GraphSection[] = [processesSection, filesSection, rolesSection];

/** `readme` with `body` between the marker's begin and end; unchanged when it has no such region. */
export function inject(readme: string, body: string, marker: string): string {
  const begin = `<!-- ${marker}:begin -->`;
  const end = `<!-- ${marker}:end -->`;
  const start = readme.indexOf(begin);
  const stop = readme.indexOf(end);
  if (start === -1 || stop === -1 || stop < start) return readme;
  return readme.slice(0, start + begin.length) + "\n\n" + body.trimEnd() + "\n\n" + readme.slice(stop);
}

/** The README with every opted-in section rendered, and what was written or left. */
export function syncReadme(root: string, readme: string): { content: string; written: string[]; notes: string[] } {
  let content = readme;
  const written: string[] = [];
  const notes: string[] = [];
  for (const s of SECTIONS) {
    if (!content.includes(`<!-- ${s.marker}:begin -->`)) continue;
    const out = s.render({ root });
    notes.push(...out.notes.map((n) => `${s.marker}: ${n}`));
    if (out.skip) continue;
    content = inject(content, out.markdown, s.marker);
    written.push(s.marker);
  }
  return { content, written, notes };
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const at = args.indexOf("--root");
  const root = at >= 0 && args[at + 1] ? args[at + 1]! : join(import.meta.dir, "..", "..", "bootstrap");
  const file = join(root, "README.md");
  if (!existsSync(file)) {
    console.error(`✗ ${file} does not exist — there is no README to write sections into, and that is not a pass.`);
    process.exit(2);
  }
  const before = readFileSync(file, "utf-8");
  const { content, written, notes } = syncReadme(root, before);
  for (const n of notes) console.log(`  · ${n}`);
  if (args.includes("--check")) {
    if (content !== before) {
      console.error(`✗ ${file}: generated sections are stale (${written.join(", ")}) — run without --check`);
      process.exit(1);
    }
    console.log(`✓ README sections current: ${written.join(", ") || "none opted in"}`);
  } else {
    if (content !== before) writeFileSync(file, content);
    console.log(`${content === before ? "=" : "✓"} README sections: ${written.join(", ") || "none opted in"}`);
  }
}
