import { describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { documentsSection, pageFooter, publishedDocuments, redirectPage, stageSite, stagedPaths } from "./site.ts";
import { generatedBanner } from "./generated-by.ts";

describe("site — what a Pages workflow publishes", () => {
  const top = mkdtempSync(join(tmpdir(), "site-"));
  const root = join(top, "demo");
  mkdirSync(join(root, "skills"), { recursive: true });
  writeFileSync(join(root, "demo.json"), JSON.stringify({ name: "demo", title: "Demo", directories: [{ id: "skills", path: "skills/", graphKinds: ["skills"] }] }));
  writeFileSync(join(root, "README.md"), "# Demo\n\n## Start\n\nSee [skills](skills/README.md).\n");
  writeFileSync(join(root, "skills", "README.md"), "# skills\n\n## Every file\n");
  spawnSync("git", ["init", "-q"], { cwd: root });

  test("the README page is README.md (served as README.html); the files sit beside it; nothing is overwritten", () => {
    const out = join(top, "_site-src");
    mkdirSync(out, { recursive: true });
    writeFileSync(join(out, "_config.yml"), "title: kept\n");
    const r = stageSite(root, out);
    expect(r.problems).toEqual([]);
    const index = readFileSync(join(out, "README.md"), "utf-8");
    expect(index).toContain("## Contents");
    expect(index).toContain("[skills](#skills)");
    expect(index).toContain("This page was generated by [bootstrap-tools]");
    expect(existsSync(join(out, "index.md"))).toBe(false);
    expect(readFileSync(join(out, "index.html"), "utf-8")).toBe(redirectPage());
    expect(existsSync(join(out, "skills", "README.md"))).toBe(true);
    expect(readFileSync(join(out, "_config.yml"), "utf-8")).toBe("title: kept\n");
    expect(r.skipped).toContain("_config.yml");
  });

  test("no declaration, no site", () => {
    expect(() => stageSite(join(top, "nothing"), join(top, "out2"))).toThrow();
  });

  test("every JSON Schema and JSON-LD document is staged at the address it names, with a .json copy of JSON-LD", () => {
    const r2 = join(top, "vocab");
    mkdirSync(join(r2, "schemas"), { recursive: true });
    writeFileSync(join(r2, "vocab.json"), JSON.stringify({ name: "vocab", version: "1.2.3", iriBase: "https://x.example/vocab/", directories: [] }));
    writeFileSync(join(r2, "README.md"), "# vocab\n");
    writeFileSync(join(r2, "schemas", "a.schema.json"), JSON.stringify({ $id: "https://x.example/vocab/1.2.3/schemas/a.schema.json" }));
    writeFileSync(join(r2, "ns.jsonld"), JSON.stringify({ "@context": {}, "@id": "https://x.example/vocab/1.2.3/ns" }));
    writeFileSync(join(r2, "elsewhere.json"), JSON.stringify({ $id: "https://other.example/x.json" }));
    spawnSync("git", ["init", "-q"], { cwd: r2 });
    const docs = publishedDocuments(r2);
    expect(docs.map((d) => [d.iri, d.path, d.kind])).toEqual([
      ["https://x.example/vocab/1.2.3/ns", "1.2.3/ns", "json-ld"],
      ["https://x.example/vocab/1.2.3/schemas/a.schema.json", "1.2.3/schemas/a.schema.json", "json-schema"],
    ]);
    expect(stagedPaths(docs[0]!)).toEqual(["1.2.3/ns", "1.2.3/ns.json"]);
    const out = join(top, "_vocab");
    const r = stageSite(r2, out);
    expect(r.problems).toEqual([]);
    for (const p of ["1.2.3/ns", "1.2.3/ns.json", "1.2.3/ns.jsonld", "1.2.3/schemas/a.schema.json"]) expect(existsSync(join(out, p)), p).toBe(true);
    expect(readFileSync(join(out, "1.2.3/ns"), "utf-8")).toBe(readFileSync(join(r2, "ns.jsonld"), "utf-8"));
    const index = readFileSync(join(out, "README.md"), "utf-8");
    expect(index).toContain('## <a id="published-documents"></a>Published documents');
    expect(index).toContain("[Published documents](#published-documents)");
    expect(documentsSection(docs)).toContain("[`https://x.example/vocab/1.2.3/ns`](1.2.3/ns) ([`.json`](1.2.3/ns.json))");
  });

  test("the default landing page redirects to README.html; an instance's own index wins", () => {
    expect(redirectPage()).toContain('<meta http-equiv="refresh" content="0; url=README.html">');
    expect(redirectPage()).toContain('<link rel="canonical" href="README.html">');
    const r3 = join(top, "landing");
    mkdirSync(r3, { recursive: true });
    writeFileSync(join(r3, "landing.json"), JSON.stringify({ name: "landing", directories: [] }));
    writeFileSync(join(r3, "README.md"), "# landing\n");
    writeFileSync(join(r3, "index.md"), "# my own front page\n");
    spawnSync("git", ["init", "-q"], { cwd: r3 });
    const out = join(top, "_landing");
    stageSite(r3, out);
    expect(existsSync(join(out, "index.html"))).toBe(false);
    expect(readFileSync(join(out, "index.md"), "utf-8")).toBe("# my own front page\n");
  });

  test("a generated page's footer names its generator and source, never an edit page; an authored one edits its SOURCE", () => {
    const repo = "https://github.com/o/r";
    const gen = `<!-- kg:subgraph:begin -->\n${generatedBanner("scripts/subgraph-readmes.ts", "the entry", "change it")}\n# x\n<!-- kg:subgraph:end -->\n`;
    expect(pageFooter("skills/README.md", gen, repo, "main")).toEqual({
      generated_by: ["scripts/subgraph-readmes.ts"],
      generated_from: "the entry",
      source_url: "https://github.com/o/r/tree/main/skills",
    });
    const partly = `# mine\n<!-- kg:toc:begin -->\n${generatedBanner("scripts/readme-sections.ts", "headings", "edit outside", "section")}\n<!-- kg:toc:end -->\n`;
    expect(pageFooter("README.md", partly, repo, "main")).toEqual({ edit_url: "https://github.com/o/r/edit/main/README.md", generated_sections: ["scripts/readme-sections.ts"] });
    expect(pageFooter("skills/a.md", "# authored\n", undefined, "main")).toEqual({});
  });

  test("the staged layout replaces the theme footer, and _config.yml scopes each page's footer", () => {
    const out = join(top, "_footer");
    const r4 = join(top, "footer");
    mkdirSync(join(r4, "skills"), { recursive: true });
    writeFileSync(join(r4, "footer.json"), JSON.stringify({ name: "footer", repository: "o/r", directories: [{ id: "skills", path: "skills/", graphKinds: ["skills"] }] }));
    writeFileSync(join(r4, "README.md"), "# footer\n");
    writeFileSync(join(r4, "skills", "a.md"), "# a\n");
    spawnSync("git", ["init", "-q"], { cwd: r4 });
    stageSite(r4, out);
    const layout = readFileSync(join(out, "_layouts", "default.html"), "utf-8");
    expect(layout).not.toContain("{% github_edit_link");
    const config = readFileSync(join(out, "_config.yml"), "utf-8");
    expect(config).toContain('  - scope: { path: "skills/a.md" }');
    expect(config).toContain('      edit_url: "https://github.com/o/r/edit/main/skills/a.md"');
    expect(config).toContain('  - scope: { path: "README.md" }');
    expect(config).toContain('      generated_by: ["scripts/readme-book.ts"]');
  });

  test("no iriBase, no document addresses: nothing claimed", () => {
    expect(publishedDocuments(root)).toEqual([]);
  });
});

