/**
 * A REQUIREMENT SET — the requirements document: a set of requirement
 * statements at one stage of its life, with the sign-offs that moved it there.
 *
 * @module bootstrap-tools/schemas/requirement-set
 * @graphNode schema
 *
 * The ask, and its approval, are on litlfred/folio-assistant issue #2405
 * (FR-010 to FR-013). Not quoted here: a bootstrap schema names no outside
 * concept, not even in a quotation (`check:bootstrap-concepts`).
 *
 * ## Why a set is its own node
 *
 * A {@link Requirement} is a statement somebody must meet, and it outlives the
 * document that proposed it. The document has a different life: it is
 * drafted, proposed, approved, planned, worked, delivered and accepted — or
 * rejected, cancelled or superseded — and each of those moves is a DECISION
 * somebody made. Before this node the stage was implied by which directory a
 * file sat in, and nothing recorded who decided, when, or why.
 *
 * ## The set's stage and each member's status are INDEPENDENT
 *
 * A requirement can be `in-force` while the set that proposed it is still
 * `delivered`, and a set can be cancelled without retiring a requirement
 * another set also carries. One link between them is enforced, by the
 * harness's checker because it needs the member files: a set is `accepted`
 * only when every member it approved is `in-force`.
 *
 * ## A sign-off is an adjudication record
 *
 * Who decided (`kind`, `id`, `actor` — the same three identity fields a
 * reviewer entry carries in the harness), when (`at`), about what (`scope`:
 * the set, or one member), what they decided (`outcome`, from a closed list),
 * which stage that moves the set to (`stage`), why (`reason`) and where the
 * decision can be read (`evidence`, a link to the comment it was made in).
 *
 * ## Which stages need a sign-off
 *
 * The ADJUDICATED stages — `approved`, `accepted`, `rejected`, `cancelled` —
 * are reached only through a sign-off that names the stage, with the matching
 * outcome; `approved` and `accepted` only through a HUMAN one. The PROGRESS
 * stages — `planned`, `in-progress`, `delivered` — are facts about the work
 * rather than decisions, and are checked as facts: from `planned` on, the set
 * names its work plan, and every stage past `approved` presupposes an approving
 * human sign-off. `draft` and `proposed` are authoring, not adjudication.
 *
 * Bootstrap holds no code, so this file is the source and
 * `bootstrap/schemas/requirement-set.schema.json` is what bootstrap publishes,
 * generated by `bun run bootstrap:schemas`. The refinement does not survive
 * the conversion; {@link REQUIREMENT_SET_JSON_SCHEMA_CONDITIONALS} restates
 * what JSON Schema can say.
 */
import { z } from "zod";

import { RequirementRefSchema } from "./requirement.ts";

/** Where a requirements document is in its life. */
export const RequirementSetStageSchema = z.enum([
  "draft", "proposed", "approved", "planned", "in-progress", "delivered", "accepted",
  "rejected", "cancelled", "superseded",
]);
export type RequirementSetStage = z.infer<typeof RequirementSetStageSchema>;

/** The stages a sign-off decides, as against those the work reaches. */
export const ADJUDICATED_STAGES = ["approved", "accepted", "rejected", "cancelled"] as const;
/** From `planned` on, a set names the work that delivers it. */
export const STAGES_WITH_WORK_PLAN = ["planned", "in-progress", "delivered", "accepted"] as const;
/** Every stage past `approved` presupposes that it was approved, by a person. */
export const STAGES_AFTER_APPROVAL = ["approved", "planned", "in-progress", "delivered", "accepted"] as const;

/** What a sign-off decided — the closed list an adjudicator answers from. */
export const SignOffOutcomeSchema = z.enum(["approve", "amend", "reject", "defer", "cancel"]);
export type SignOffOutcome = z.infer<typeof SignOffOutcomeSchema>;

/** The outcomes that may establish each adjudicated stage. */
export const OUTCOMES_FOR_STAGE: Record<(typeof ADJUDICATED_STAGES)[number], readonly SignOffOutcome[]> = {
  approved: ["approve", "amend"],
  accepted: ["approve"],
  rejected: ["reject"],
  cancelled: ["cancel"],
};

/** Who signed: a deterministic program, an agent, or a person. */
export const SignerKindSchema = z.enum(["script", "agent", "human"]);

/** What one member's sign-off decided about it. */
export const MemberDecisionSchema = z.enum(["approved", "amended", "rejected", "deferred"]);

/** `reqset:<slug>`. */
export const RequirementSetIdSchema = z
  .string()
  .regex(/^reqset:[a-z0-9][a-z0-9-]*$/, "a requirement set id is `reqset:<lowercase-slug>`");

/** A date, or a date-time with an offset. */
const WhenSchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2}(\.\d+)?)?(Z|[+-]\d{2}:\d{2}))?$/,
    "`at` is a date (YYYY-MM-DD) or a date-time with an offset");

/** One recorded decision about a set, or about one of its members. */
export const SignOffSchema = z.object({
  kind: SignerKindSchema,
  /** Stable identifier — a login, an agent's name, a script path. */
  id: z.string().min(1),
  /** The declared actor this signer acted as, when the harness declares actors. */
  actor: z.string().min(1).optional(),
  at: WhenSchema,
  /** The set's id, or a member's reference. */
  scope: z.string().regex(/^(reqset:[a-z0-9][a-z0-9-]*|req:[a-z0-9][a-z0-9-]*(#[A-Za-z0-9][A-Za-z0-9_.-]*)?)$/,
    "a sign-off's scope is the set (`reqset:<slug>`) or one member (`req:<slug>[#<key>]`)"),
  outcome: SignOffOutcomeSchema,
  /** The stage this sign-off moves the set to, when its scope is the set. */
  stage: RequirementSetStageSchema.optional(),
  /** Why — the dispensation, in the signer's words or quoting them. */
  reason: z.string().min(1).optional(),
  /** Where the decision can be read: a link to the comment it was made in. */
  evidence: z.string().regex(/^https:\/\/\S+$/, "evidence is an https link to where the decision was made"),
});
export type SignOff = z.infer<typeof SignOffSchema>;

export const RequirementSetMemberSchema = z.object({
  ref: RequirementRefSchema,
  decision: MemberDecisionSchema.optional(),
});

/** The set's FIELDS, before its refinement — for a harness to extend. */
export const RequirementSetFields = z.object({
  id: RequirementSetIdSchema,
  title: z.string().min(1),
  /** The requirements methodology that governs it, by the harness's own name for it. */
  methodology: z.string().min(1),
  /** The issue (or other review surface) the set is decided on. */
  issue: z.string().regex(/^https:\/\/\S+$/).optional(),
  stage: RequirementSetStageSchema,
  members: z.array(RequirementSetMemberSchema).min(1),
  /** The work plan: work-item ids, one or more per member. */
  workPlan: z.array(z.string().min(1)).optional(),
  signOffs: z.array(SignOffSchema).optional(),
  /** Where the document is, as a path or a link. */
  document: z.string().min(1).optional(),
  supersededBy: RequirementSetIdSchema.optional(),
});

type SetLike = {
  id: string; stage: RequirementSetStage; workPlan?: string[]; signOffs?: SignOff[];
  supersededBy?: string; members: { ref: string }[];
};

/** The sign-offs scoped to the set itself. */
export function setSignOffs(s: { id: string; signOffs?: SignOff[] }): SignOff[] {
  return (s.signOffs ?? []).filter((o) => o.scope === s.id);
}

/**
 * Why a set at its stage is not justified by its own record — empty when it
 * is. The one function both the schema refinement and a harness's checker use,
 * so a checker that also reads sign-offs kept elsewhere passes the union here.
 */
export function requirementSetProblems(s: SetLike): { path: (string | number)[]; message: string }[] {
  const out: { path: (string | number)[]; message: string }[] = [];
  const own = setSignOffs(s);
  const adjudicated = (ADJUDICATED_STAGES as readonly string[]).includes(s.stage);
  if (adjudicated) {
    const st = s.stage as (typeof ADJUDICATED_STAGES)[number];
    const ok = own.some((o) => o.stage === st && OUTCOMES_FOR_STAGE[st].includes(o.outcome)
      && (st === "approved" || st === "accepted" ? o.kind === "human" : true)
      && (st === "cancelled" ? !!o.reason : true));
    if (!ok) {
      const who = st === "approved" || st === "accepted" ? "a HUMAN sign-off" : "a sign-off";
      const extra = st === "cancelled" ? " and a reason" : "";
      out.push({ path: ["signOffs"], message: `a set at \`${st}\` needs ${who} scoped to it, naming stage \`${st}\` with outcome ${OUTCOMES_FOR_STAGE[st].map((x) => `\`${x}\``).join(" or ")}${extra}` });
    }
  }
  if ((STAGES_AFTER_APPROVAL as readonly string[]).includes(s.stage) && s.stage !== "approved") {
    if (!own.some((o) => o.stage === "approved" && o.kind === "human" && OUTCOMES_FOR_STAGE.approved.includes(o.outcome))) {
      out.push({ path: ["signOffs"], message: `a set at \`${s.stage}\` was never approved: no human sign-off moved it to \`approved\`` });
    }
  }
  if ((STAGES_WITH_WORK_PLAN as readonly string[]).includes(s.stage) && (s.workPlan ?? []).length === 0) {
    out.push({ path: ["workPlan"], message: `a set at \`${s.stage}\` names its work plan — at least one work item` });
  }
  if (s.stage === "superseded" && !s.supersededBy) {
    out.push({ path: ["supersededBy"], message: "a superseded set names what superseded it" });
  }
  const members = new Set(s.members.map((m) => m.ref.split("#")[0]));
  (s.signOffs ?? []).forEach((o, i) => {
    if (o.scope !== s.id && !members.has(o.scope.split("#")[0])) {
      out.push({ path: ["signOffs", i, "scope"], message: `\`${o.scope}\` is neither this set nor one of its members` });
    }
  });
  return out;
}

export function refineRequirementSet(s: SetLike, ctx: z.RefinementCtx): void {
  for (const p of requirementSetProblems(s)) ctx.addIssue({ code: "custom", path: p.path, message: p.message });
}

export const RequirementSetSchema = RequirementSetFields.superRefine(refineRequirementSet);
export type RequirementSet = z.infer<typeof RequirementSetSchema>;

const signOffNaming = (stage: string, outcomes: readonly string[], extra: Record<string, unknown> = {}, required: string[] = []) => ({
  contains: {
    type: "object",
    properties: { stage: { const: stage }, outcome: { enum: [...outcomes] }, ...extra },
    required: ["stage", "outcome", ...required],
  },
});

/**
 * THE PART THE CONVERTER DROPS, as far as JSON Schema can say it: the
 * adjudicated stages' sign-offs, the work plan, and a superseded set's
 * successor. What it cannot say — that the sign-off's scope is THIS set, and
 * that a scope names a member — is checked through {@link requirementSetProblems}.
 */
export const REQUIREMENT_SET_JSON_SCHEMA_CONDITIONALS = [
  {
    if: { properties: { stage: { const: "superseded" } }, required: ["stage"] },
    then: { required: ["supersededBy"] },
  },
  {
    if: { properties: { stage: { enum: [...STAGES_WITH_WORK_PLAN] } }, required: ["stage"] },
    then: { required: ["workPlan"], properties: { workPlan: { minItems: 1 } } },
  },
  ...(["approved", "accepted"] as const).map((st) => ({
    if: { properties: { stage: { const: st } }, required: ["stage"] },
    then: { required: ["signOffs"], properties: { signOffs: signOffNaming(st, OUTCOMES_FOR_STAGE[st], { kind: { const: "human" } }, ["kind"]) } },
  })),
  {
    if: { properties: { stage: { const: "rejected" } }, required: ["stage"] },
    then: { required: ["signOffs"], properties: { signOffs: signOffNaming("rejected", OUTCOMES_FOR_STAGE.rejected) } },
  },
  {
    if: { properties: { stage: { const: "cancelled" } }, required: ["stage"] },
    then: { required: ["signOffs"], properties: { signOffs: signOffNaming("cancelled", OUTCOMES_FOR_STAGE.cancelled, {}, ["reason"]) } },
  },
] as const;
